---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
generators:
  - ./generator.yml

resources:
  - ./placements/placement.yml
  - ./placements/placementbinding.yml
  - ./placements/policyset.yml