---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: application-certmanager
  namespace: openshift-gitops
spec:
  destination:
    namespace: acm-policies
    #namespace: openshift-gitops
    server: https://kubernetes.default.svc
  project: default
  source:
    path: operators/cert-manager
    repoURL: https://github.com/luisevm/acm-gitops-demo.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
    - CreateNamespace=true
